### ISSUE TITLE
XML parsing fails with valid XML and XPaths

### ISSUE THREAD

**Issue by P403n1x87** [santhosh-tekuri/jlibs#79]
While testing one of my applications, I stumbled upon this interesting problem. Here is the setup.

I'm using the following sample message:
~~~ xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<test>
  <type>MSG_TYPE</type>
  <contactDetails>
    <name>John</name>
    <surname>Doe</surname>
  </contactDetails>
  <contactDetails>
    <name>John</name>
    <surname>Doe</surname>
  </contactDetails>
  <contactDetails>
    <name>John</name>
    <surname>Doe</surname>
  </contactDetails>
  <pingpong>
    <trip>0</trip>
    <comment>hello</comment>
  </pingpong>
</test>
~~~
The essential detail here is that the `<contactDetail>` node is repeated at least three times, with the same subnodes and with the same content. If the middle entry is changed from John Doe to Albert Smith, or even Albert Doe, the issue is not reproducible. However, changing the third occurrence causes the problem too.

I have the following XPath registered with Xmldog: `/test/contactDetails/name/text()` and `/test/contactDetails/surname/text()`.

With this scenario, I get the following stack trace

~~~
oracle.xml.parser.v2.XMLParseException; lineNumber: 1; columnNumber: 1; Start of root element expected.
        at oracle.xml.parser.v2.XMLError.flushErrors1(XMLError.java:326)
        at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:453)
        at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:394)
        at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:236)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:189)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:174)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:205)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:212)
        ...
--------------- linked to ------------------
javax.xml.xpath.XPathException: oracle.xml.parser.v2.XMLParseException; lineNumber: 1; columnNumber: 1; Start of root element expected.
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:192)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:174)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:205)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:212)
        ...
Caused by: oracle.xml.parser.v2.XMLParseException; lineNumber: 1; columnNumber: 1; Start of root element expected.
        at oracle.xml.parser.v2.XMLError.flushErrors1(XMLError.java:326)
        at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:453)
        at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:394)
        at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:236)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:189)
        ... 8 more
--------------- linked to ------------------
javax.xml.xpath.XPathException: javax.xml.xpath.XPathException: oracle.xml.parser.v2.XMLParseException; lineNumber: 1; columnNumber: 1; Start of root element expected.
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:176)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:205)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:212)
        ...
Caused by: javax.xml.xpath.XPathException: oracle.xml.parser.v2.XMLParseException; lineNumber: 1; columnNumber: 1; Start of root element expected.
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:192)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:174)
        ... 7 more
Caused by: oracle.xml.parser.v2.XMLParseException; lineNumber: 1; columnNumber: 1; Start of root element expected.
        at oracle.xml.parser.v2.XMLError.flushErrors1(XMLError.java:326)
        at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:453)
        at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:394)
        at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:236)
        at jlibs.xml.sax.dog.XMLDog.sniff(XMLDog.java:189)
        ... 8 more
~~~

**Comment by santhosh-tekuri** [comment]
`Caused by: oracle.xml.parser.v2.XMLParseException; lineNumber: 1; columnNumber: 1; Start of root element expected.`

this means the xml is invalid.
check that xml feeded is correct

**Comment by P403n1x87** [comment]
Many thanks for getting back to me about this. The XML I'm using is the one I posted in the issue. Online validators give the thumb up and the XPaths also match as expected.

I understand three stack trace shows a problem with oracle, but would this be enough to rule out a problem with XMLDog? Sorry for this but I haven't had the chance to have a look into the code.

Many thanks for your help.

**Comment by santhosh-tekuri** [comment]
> The XML I'm using is the one I posted in the issue
this may not be the case.

replace the xmldog code with sax-parsing code. then you will find that you will still get the exception.

it may be the case that you are using reader to print the xml to console, and then passing it to xmldog.
because the entire xml is already read to print on console, xmldog got nothing. thus it says invalid xml.

try to create small test to reproduce the issue. then I can help in identifying the problem

**Comment by P403n1x87** [comment]
Thanks for your support. The tests were passing but there was a problem somewhere in my code that I managed to fix.
